---

- hosts: all
  become: true
  tasks:
  
  - name: install updates (CentOS)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages and updates them  (UBUNTU)
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package: 
      name: samba
      state: latest


- hosts: db_servers
  become: true
  tasks: 
  
  - name: install mariadb package (CentOS)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

