---

- hosts: all
  become: true


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages and updates them  (UBUNTU)
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


- hosts: file_servers
  become: true


- hosts: db_servers
  become: true
